// generated by stringer -type Class; DO NOT EDIT

package matfio

import "fmt"

const _Class_name = "CellClassStructClassObjectClassCharClassSparseClassFloat64ClassFloat32ClassInt8ClassUint8ClassInt16ClassUint16ClassInt32ClassUint32ClassInt64ClassUint64Class"

var _Class_index = [...]uint8{0, 9, 20, 31, 40, 51, 63, 75, 84, 94, 104, 115, 125, 136, 146, 157}

func (i Class) String() string {
	i -= 1
	if i >= Class(len(_Class_index)-1) {
		return fmt.Sprintf("Class(%d)", i+1)
	}
	return _Class_name[_Class_index[i]:_Class_index[i+1]]
}
